CREATE TABLE elko_product
(
    elpr_id serial NOT NULL,
    id integer,
    elko_code integer,
    name text,
    manufacturer_code text,
    vendor_name text,
    vendor_code text,
    catalog text,
    quantity text,
    price numeric(18, 2),
    discount_price numeric(18, 2),
    image_path text,
    thumbnail_image_path text,
    full_description text,
    currency text,
    http_description text,
    packaging_quantity smallint,
    warranty text,
    ean_code text,
    obligatory_kit smallint,
    reserved_quantity smallint,
    prom_date smallint,
    prom_quant smallint,
    quantity_for_price_2 text,
    price_2 numeric(18, 2),
    lot_number text,
    copyright_tax numeric(18, 2),
    incoming_quantity integer,
    product_description_json json,
    version_nr integer NOT NULL,
    PRIMARY KEY (elpr_id)
);